title: Enzo Incutti
description: I build systems that catch bugs before humans do.
author: Enzo Incutti
email: vincenzo.incutti@gmail.com

url: "https://enzoincutti.com"
baseurl: ""

# Social links
social:
  github: enzo-inc
  twitter: enzo__inc
  linkedin: vincenzo-incutti

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
